name: foldls
version: '0.0.1'
synopsis: See readme.md
description: See readme.md for description.
category: project
author: Tony Day
maintainer: tonyday567@gmail.com
copyright: Tony Day (c) 2017
license: BSD3
github: tonyday567/sfold
default-extensions:
- BangPatterns
- BinaryLiterals
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DisambiguateRecordFields
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTSyntax
- InstanceSigs
- KindSignatures
- LambdaCase
- MonadComprehensions
- MultiParamTypeClasses
- MultiWayIf
- NegativeLiterals
- NoImplicitPrelude
- OverloadedStrings
- ParallelListComp
- PartialTypeSignatures
- PatternSynonyms
- RankNTypes
- RecordWildCards
- RecursiveDo
- ScopedTypeVariables
- TupleSections
- TypeFamilies
- TypeOperators
- UnicodeSyntax
dependencies:
- base >=4.7 && <5
library:
  source-dirs: src
  ghc-options:
  - -funbox-strict-fields
  - -fforce-recomp
  exposed-modules:
  - Control.Foldl.Folds
  dependencies:
  - protolude
  - foldl
  - containers
tests:
  test:
    main: test.hs
    source-dirs: test
    dependencies:
    - doctest
    - protolude
